ALTER TABLE visits ADD COLUMN IF NOT EXISTS copay_collected NUMERIC(10,2);
ALTER TABLE visits ADD COLUMN IF NOT EXISTS wd_verified BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE visits ADD COLUMN IF NOT EXISTS patient_signed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE visits ADD COLUMN IF NOT EXISTS supervising_staff_id TEXT;
